stages:
    - pre_test
    - build 
    - test
    
gpu_test_pre:
    stage: pre_test
    tags:
        - atsccs68-shell
    before_script:
        - git branch -vva
        - echo $commit_author_name
    script:
        - echo "checking availability of atscc68" $HOST
        - echo $GPU_VENDOR $GPU_MODEL
        - git --version
        
ci_builder_pre:
    stage: pre_test
    tags:
        - ci_testing_cc
    before_script:
        - git branch -vva
        - echo $commit_author_name
    script:
        - echo "checking availability of ci_testing_cc"
        - git --version

ci_builder_build:
    stage: build
    tags:
        - ci_testing_cc
    before_script:
        - cat .git/config
        - git submodule set-url submodules/xdmfwriter https://github.com/TUM-I5/XdmfWriter.git
        - git submodule set-url submodules/cxxtest https://github.com/CxxTest/cxxtest.git
        - git submodule set-url submodules/utils https://github.com/TUM-I5/utils.git
        - git submodule set-url submodules/async https://github.com/TUM-I5/ASYNC.git
        - git submodule set-url submodules/scons-tools https://github.com/TUM-I5/scons-tools.git
        - git submodule set-url submodules/PUML https://github.com/TUM-I5/PUML2.git
        - git submodule set-url submodules/easi https://github.com/SeisSol/easi.git
        - git submodule set-url submodules/yaml-cpp https://github.com/jbeder/yaml-cpp.git  
        - git submodule set-url submodules/ImpalaJIT https://github.com/uphoffc/ImpalaJIT.git
        - git submodule set-url submodules/yateto https://github.com/SeisSol/yateto.git
        - git submodule set-url submodules/eigen3 https://github.com/eigenteam/eigen-git-mirror
        - git submodule set-url submodules/Device https://github.com/SeisSol/Device.git
        - git submodule --quiet update --init --recursive 
        - wget -q https://syncandshare.lrz.de/dl/fiJNAokgbe2vNU66Ru17DAjT/netcdf-4.6.1.tar.gz
        - wget -q https://github.com/hfp/libxsmm/archive/master.zip
        - sudo apt-get install gcc-8 g++-8 gfortran-8
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
        - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 100
        - sudo apt-get install -qq --yes openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-dev python3 python3-pip libmetis-dev libparmetis-dev cxxtest
        - gfortran --version
        - pip3 install --upgrade pip
        - pip3 install 'numpy>=1.12.0'
        - pip3 install lxml
        - pip3 install setuptools
        - pip3 install sphinx
        - pip3 install sphinx_rtd_theme
        - cd netcdf-4.6.1 && CC=h5pcc ./configure --prefix=/usr --enable-shared=no --disable-dap && make && sudo make install && cd ..
        - unzip master.zip
        - cd libxsmm-master && make generator && sudo cp bin/libxsmm_gemm_generator /usr/bin && cd ..
    script:
        - echo "now building"
        - cat .git/config
        
gpu_test_build:
    stage: build
    tags:
        - atsccs68-shell
    allow_failure: true
    before_script:
        - git branch -vva
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
    script:
        - echo "now building"
        - git clone --recurse-submodules https://github.com/SeisSol/SeisSol
        - git clone https://github.com/7bits-register/convergence-tests.git tests
        - ls
        - cat /etc/os-release
        - cat test_singularity.sh
        - chmod +x test_singularity.sh
        - which singularity 
        - singularity --version
        - singularity pull library://7bits-register/collection/seissol_base_amd64.sif:sha256.ab10184df265ef283a99d3b4c1a6b9d2e05ed5945ca43838c9d9a3b8d5b18cf9 
        #singularity pull library://7bits-register/collection/seissol_base_arm64.sif:sha256.908e862805afde41dc6910ba122361fae65268856b9798db1e087babc17e2171
        - ls
        - singularity run --nv -B $PWD:/home/$(whoami) --env GPU_VENDOR=nvidia --env GPU_MODEL=sm_61 --env HOST=snb ./seissol_base_amd64.sif_sha256.ab10184df265ef283a99d3b4c1a6b9d2e05ed5945ca43838c9d9a3b8d5b18cf9.sif ./test_singularity.sh
        #- singularity run --nv -B $PWD:/home/$(whoami) --env GPU_VENDOR=nvidia --env GPU_MODEL=sm_61 --env HOST=snb ./seissol-base.sif_sha256.908e862805afde41dc6910ba122361fae65268856b9798db1e087babc17e2171.sif ./test_singularity.sh
