stages:
    - pre_test
    - build 
    
atsccs68:
    stage: pre_test
    tags:
        - atsccs68-shell
    script:
        - whoami
        - pwd
        - echo $PATH
        - echo $NAME_TEST
    stage:  build
    tags:
        - atsccs68-shell
    script:
        - whoami
        - pwd
        - git clone --recurse-submodules https://github.com/SeisSol/SeisSol
        - git clone https://github.com/7bits-register/convergence-tests.git tests
        - ls
        - cat /etc/os-release
        - cat test_singularity.sh
        - chmod +x test_singularity.sh
        - which singularity 
        - singularity --version
        #- singularity pull --arch amd64 library://7bits-register/collection/seissol-base.sif:gcc-8.3.0_openmpi-3.1.5_cuda-10.1.243_stable
        - singularity pull library://7bits-register/collection/seissol-base.sif:sha256.3dfa7466a4dbe097a755e2779d8612a71e81d60522bff9b90a35b4b1dc5b97c9
        
dbuilder:
    stage: pre_test
    tags:
        - ci_testing_cc
    before_script:
        - git branch -vva
        #- git log --format="%H" -n 1
        #- git log --format="%H" -n 1 > commit_id
        #- git --no-pager show -s --format='%ae' $commit_id
        #- commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
    stage: build
    tags:
        - dbuilder_cc
    before_script:
        - git branch -vva
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
        - git submodule --quiet sync --recursive
        - git submodule --quiet update --init --recursive
        - wget -q https://syncandshare.lrz.de/dl/fiJNAokgbe2vNU66Ru17DAjT/netcdf-4.6.1.tar.gz
        - wget -q https://github.com/hfp/libxsmm/archive/master.zip
        - sudo apt-get install gcc-8 g++-8 gfortran-8
        
ci_builder:
    stage: pre_test
    tags:
        - ci_testing_cc
    before_script:
        - git branch -vva
        #- git log --format="%H" -n 1
        #- git log --format="%H" -n 1 > commit_id
        #- git --no-pager show -s --format='%ae' $commit_id
        #- commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
    script:
        - whoami
        - pwd
        - echo $PATH
        - echo $NAME_TEST
        #- git clone --recurse-submodules https://github.com/SeisSol/SeisSol
        #- git clone https://github.com/7bits-register/convergence-tests.git tests
        #- singularity pull --arch amd64 library://7bits-register/collection/seissol-base.sif:gcc-8.3.0_openmpi-3.1.5_cuda-10.1.243_stable
