stages:
    - pre_test
    - build 
    

dbuilder:
    stage: pre_test
    tags:
        - dbuilder_cc
    script:
        - whoami
        - pwd
        - echo $HOST_ARCH
        - echo $NAME_TEST
        - git branch -vva
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
        - cat test_singularity_cpu.sh
        
dbuilder_2:
    stage: build
    tags:
        - dbuilder_cc
    script:
        - git log --format="%H" -n 1
        - git log --format="%H" -n 1 > commit_id
        - git --no-pager show -s --format='%ae' $commit_id
        - commit_author_name=$(git --no-pager show -s --format='%ae' $commit_id) 
        - echo $commit_author_name
        - export PATH=$PATH:/home/ubuntu/singularity/bin
        - git clone https://github.com/7bits-register/convergence-tests.git tests
        - singularity pull docker://ravilmobile/seissol_base_amd64:ubuntu-1804_gcc-8.3.0_openmpi-3.1.5
        - ls -lh
        - cat test_singularity_cpu.sh
        - singularity run -B $PWD:/home/$(whoami) ./seissol_base_amd64_ubuntu-1804_gcc-8.3.0_openmpi-3.1.5.sif ./test_singularity_cpu.sh
        
ci_builder:
    stage: pre_test
    tags:
        - ci_testing_cc
    before_script:
        - git branch -vva
        - echo $commit_author_name
    script:
        - whoami
        - pwd
        - echo $PATH
        - echo $NAME_TEST
        #- git clone --recurse-submodules https://github.com/SeisSol/SeisSol
        #- git clone https://github.com/7bits-register/convergence-tests.git tests
        #- singularity pull --arch amd64 library://7bits-register/collection/seissol-base.sif:gcc-8.3.0_openmpi-3.1.5_cuda-10.1.243_stable
