stages:
    - pre_test
    - build 
    - test
    
gpu_test_pre:
    stage: pre_test
    tags:
        - atsccs68-shell
    before_script:
        - git branch -vva
        - echo $commit_author_name
    script:
        - echo "checking availability of atscc68" $HOST
        - echo $GPU_VENDOR $GPU_MODEL
        - git --version
        
ci_builder_pre:
    stage: pre_test
    tags:
        - ci_testing_cc
    before_script:
        - git branch -vva
        - echo $commit_author_name
    script:
        - echo "checking availability of ci_testing_cc"
        - git --version

ci_builder_build:
    stage: build
    tags:
        - ci_testing_cc
    before_script:
        - cat .git/config
    script:
        - echo "now building"
        - cat .git/config
        
gpu_test_build:
    stage: build
    tags:
        - atsccs68-shell
    before_script:
        - cat .git/config
    script:
        - echo "now building"
        - cat .git/config
